### ISSUE TITLE
 Browser prediction

### ISSUE THREAD

**Issue by Yiquan-lol** [ali-sheikhi/Deep-Learning-Web-Services#1]
Hello, I can use command line prediction normally, but I can't get results when I use browser prediction.As shown in the picture, is there anything wrong with it?
![image](https://user-images.githubusercontent.com/57313929/103459601-a7eac900-4d4b-11eb-89eb-430ece414755.png)

**Comment by ali-sheikhi** [comment]
> Hello, I can use command line prediction normally, but I can't get results when I use browser prediction.As shown in the picture, is there anything wrong with it?

Hi,
I tested it using Chrome. Can you check if it works there? Also, in browser console (ctrl+shift+i for Chrome), go to the Network tab and disable caching.

**Comment by Yiquan-lol** [comment]
I did as you said, but the result is still not shown. One more question. Do you operate under Windows system?

**Comment by ali-sheikhi** [comment]
I use both but this project was done in Windows. I can't think of any reason why it wouldn't work in Ubuntu.

**Comment by ali-sheikhi** [comment]
You got the server running so I assume you are using "export" instead of "set" in "set FLASK_APP=predict_app.py"

Run again with debugger ("export FLASK_DEBUG=1") and check to see if there are any errors.

**Comment by Yiquan-lol** [comment]
There is two problem:
Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64 
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
I don't know if it's because of this

**Comment by Yiquan-lol** [comment]
There are two problems:
Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
I don't know if it's because of this. How can I do it?

**Comment by ali-sheikhi** [comment]
You can ignore the second one. It's just a warning about the optimizer which is only used during training. This is probably due to incompatibility issues with current Keras version and the one used during training.

The first error has to do with TF support for your CUDA version, you'd have to build it from source if you want to use your GPU (check here https://github.com/tensorflow/tensorflow/issues/38578).
I just tested it again on CPU and it runs fine. Make sure to use a clean environment, preferably Conda, to avoid package conflicts.

Update: I just cleaned up the code a little in vgg, yolo and predict python files. For example, I imported tensorflow in one the files but it was unnecessary which could be the source of the error.

**Comment by Yiquan-lol** [comment]
I used a clean environment, and I can do this in command line prodection, but not in browser proection and I'm not sure if this is a problem with TensorFlow

**Comment by ali-sheikhi** [comment]
Again, from the error you posted, the issue is in all likelihood a compatibility issue between TF(probably Keras TF backend) and your cuda version.

One thing you could try is to force Keras to use CPU instead of GPU (check this https://zkf85.github.io/2019/01/23/how-to-force-keras-use-cpu) in VGG16c_d.py.

Another approach worth trying is not using to requirements.txt to install the packages. Instead just run the code and install the packages individually as they throw an error. Most entries in requirements.txt are support packages so it won't take long. This will help in identifying the cause of the error and will make it easier to resolve it.
